# Generated by Django 5.2.5 on 2025-10-24 16:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('descompensacion', 'Descompensación'), ('tecnico', 'Apoyo Técnico'), ('disciplinario', 'Disciplinario'), ('salud', 'Salud')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('resuelta', 'Resuelta')], default='pendiente', max_length=15)),
                ('tiempo_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraIncidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_suceso', models.TextField(verbose_name='Descripción de lo sucedido')),
                ('hora_registro', models.DateTimeField(auto_now_add=True)),
                ('alerta_asociada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.alerta')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre_apoderado', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_apoderado', models.CharField(blank=True, max_length=15, null=True)),
                ('email_apoderado', models.EmailField(blank=True, max_length=254, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='core.curso')),
            ],
        ),
        migrations.AddField(
            model_name='alerta',
            name='estudiante_implicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estudiante'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('profesor', 'Profesor'), ('convivencia', 'Convivencia'), ('utp', 'UTP'), ('inspectoría', 'Inspectoría'), ('director', 'Director')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('atrasado', 'Atrasado'), ('justificado', 'Justificado')], max_length=15)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'fecha')},
            },
        ),
    ]
