# Generated by Django 5.2.5 on 2025-10-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='hora_retiro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('descompensacion', 'Descompensación'), ('tecnico', 'Apoyo Técnico'), ('disciplinario', 'Disciplinario'), ('salud', 'Salud'), ('sos', 'SOS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('atrasado', 'Atrasado'), ('justificado', 'Justificado'), ('retirado', 'Retirado')], max_length=15),
        ),
    ]
