# Generated by Django 5.2.5 on 2025-10-29 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asistencia_hora_retiro_alter_alerta_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'perfil__rol': 'profesor'}, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
    ]
