# Generated by Django 5.2.5 on 2025-10-29 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_perfil_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='estudiante_implicado',
        ),
        migrations.AddField(
            model_name='alerta',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.curso'),
        ),
        migrations.AddField(
            model_name='bitacoraincidente',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estudiante'),
        ),
    ]
