# Generated by Django 5.2.5 on 2025-10-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_alerta_estudiante_implicado_alerta_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraincidente',
            name='subtipo_descompensacion',
            field=models.CharField(blank=True, choices=[('emocional', 'Emocional'), ('convivencia', 'Convivencia')], max_length=20, null=True, verbose_name='Subtipo de Descompensación'),
        ),
    ]
