# Generated by Django 5.2.5 on 2025-10-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bitacoraincidente_subtipo_descompensacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('profesor', 'Profesor'), ('convivencia', 'Convivencia Escolar'), ('utp', 'UTP'), ('inspectoria', 'Inspectoría General'), ('director', 'Director')], max_length=20),
        ),
    ]
