# Generated by Django 5.2.5 on 2025-11-11 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_perfil_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='estudiante_implicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estudiante'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('descompensacion', 'Descompensación'), ('tecnico', 'Apoyo Técnico'), ('disciplinario', 'Disciplinario'), ('salud', 'Salud'), ('sos', 'SOS'), ('asistencia', 'Asistencia menor al 85%)')], max_length=20),
        ),
    ]
