# Generated by Django 5.2.5 on 2025-11-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alerta_estudiante_implicado_alter_alerta_creada_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('descompensacion', 'Descompensación'), ('tecnico', 'Apoyo Técnico'), ('disciplinario', 'Disciplinario'), ('salud', 'Salud'), ('sos', 'SOS'), ('asistencia', 'Asistencia menor al 85%')], max_length=20),
        ),
    ]
