# Generated by Django 5.2.5 on 2025-11-12 16:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_alerta_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='descripcion_profesor',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del profesor'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT (sin puntos, con guión)'),
        ),
        migrations.CreateModel(
            name='AsistenciaSubvencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_cierre', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('tomada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('curso', 'fecha')},
            },
        ),
    ]
